// Command licensesdoc maintains the generated Go-module section of
// THIRD_PARTY_LICENSES.md from a go-licenses CSV report. The go-licenses
// version is pinned in exactly one place — GO_LICENSES_VERSION in the
// test-go-analysis job of .github/workflows/ci.yml. The report is taken over
// the SHIPPED binary's build graph — GOOS=linux, CGO_ENABLED=0, the
// Dockerfile's build environment — because the graph is GOOS-dependent
// (measured 2026-08-28: github.com/ncruces/go-strftime enters only off-linux),
// and go run would cross-compile the tool itself under that env, so install
// first and run the host binary with the env set:
//
//	go install github.com/google/go-licenses@<GO_LICENSES_VERSION>
//	GOOS=linux CGO_ENABLED=0 go-licenses report ./cmd/ovumcy | go run ./scripts/licensesdoc -write
//	GOOS=linux CGO_ENABLED=0 go-licenses report ./cmd/ovumcy | go run ./scripts/licensesdoc -check
//
// -write rewrites the block between the BEGIN/END markers in place; -check
// exits non-zero when the committed block differs from what the report on
// stdin generates, printing which rows diverged. CI runs the -check form, so a
// dependency change that lands without regenerating the inventory fails the
// build rather than silently un-truing the file's completeness claim.
//
// The transform is deliberately deterministic across platforms: go-licenses
// joins URL path segments with the OS separator (measured on Windows: remote
// https URLs arrive with backslashes inside the path), so every backslash in
// the URL column is normalized to a forward slash before the rows are sorted.
// Any URL-column shape that is not a portable https link after that — the
// literal Unknown, a filesystem path, whatever a future release emits — is
// refused rather than committed as a dead or machine-local link.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

const (
	inventoryPath = "THIRD_PARTY_LICENSES.md"
	beginMarker   = "<!-- BEGIN GO MODULE LICENSES (generated by scripts/licensesdoc; do not edit by hand) -->"
	endMarker     = "<!-- END GO MODULE LICENSES -->"
	// ownModule's row reports the application's own license, which the file's
	// prologue already states; the inventory lists third-party packages only.
	ownModule = "github.com/ovumcy/ovumcy-web"
)

// overrides records the packages whose go-licenses row is wrong or missing,
// with the correction a human made by reading the pinned version's license
// files. Two guards keep an override from outliving its verification: it is
// pinned to the exact row go-licenses reports (post-normalization), so a
// changed report — a moved URL, a reclassification — refuses instead of
// silently emitting the stale hand-pinned row; and the version its URL embeds
// is checked against go.mod, which catches a bump even for a row whose
// reported shape is the version-free Unknown/Unknown. An override whose key
// matches no reported row refuses too, so a renamed row cannot quietly
// resurrect the wrong license.
var overrides = map[string]struct{ reportedURL, reportedLicense, url, license string }{
	// Standard BSD-3-Clause text; go-licenses cannot classify the layout and
	// reports Unknown/Unknown.
	"modernc.org/mathutil": {
		reportedURL: "Unknown", reportedLicense: "Unknown",
		url: "https://gitlab.com/cznic/mathutil/-/blob/v1.7.1/LICENSE", license: "BSD-3-Clause",
	},
	// go-licenses picks LICENSE-3RD-PARTY.md (a notices file) and calls the
	// module MIT; the module's own root LICENSE is the standard BSD-3-Clause
	// text ("The Libc Authors").
	"modernc.org/libc": {
		reportedURL: "https://gitlab.com/cznic/libc/blob/v1.73.4/LICENSE-3RD-PARTY.md", reportedLicense: "MIT",
		url: "https://gitlab.com/cznic/libc/-/blob/v1.73.4/LICENSE", license: "BSD-3-Clause",
	},
	// Same shape with a coincidentally matching name: go-licenses links
	// LICENSE-GO (the Go project's license, carried for stdlib-derived code)
	// while the module's own grant is the root LICENSE ("The Memory Authors").
	"modernc.org/memory": {
		reportedURL: "https://gitlab.com/cznic/memory/blob/v1.11.0/LICENSE-GO", reportedLicense: "BSD-3-Clause",
		url: "https://gitlab.com/cznic/memory/-/blob/v1.11.0/LICENSE", license: "BSD-3-Clause",
	},
}

func main() {
	write := flag.Bool("write", false, "rewrite the generated block in "+inventoryPath)
	check := flag.Bool("check", false, "verify the generated block matches the report on stdin")
	flag.Parse()
	if *write == *check {
		fmt.Fprintln(os.Stderr, "licensesdoc: pass exactly one of -write or -check")
		os.Exit(2)
	}

	goMod, err := os.ReadFile("go.mod")
	if err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}
	if err := verifyOverridePins(string(goMod)); err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}

	table, err := tableFromReport(bufio.NewScanner(os.Stdin))
	if err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}

	document, err := os.ReadFile(inventoryPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}
	updated, current, err := replaceBlock(string(document), table)
	if err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}

	if *check {
		if current != table {
			fmt.Fprintf(os.Stderr, "licensesdoc: %s is stale — regenerate it (the go-licenses version is GO_LICENSES_VERSION in .github/workflows/ci.yml; the env pins the shipped binary's graph):\n\n    go install github.com/google/go-licenses@<GO_LICENSES_VERSION>\n    GOOS=linux CGO_ENABLED=0 go-licenses report ./cmd/ovumcy | go run ./scripts/licensesdoc -write\n\n%s\n", inventoryPath, diffSummary(current, table))
			os.Exit(1)
		}
		fmt.Println("licensesdoc: inventory matches the dependency report.")
		return
	}
	if err := os.WriteFile(inventoryPath, []byte(updated), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("licensesdoc: wrote the generated block in %s.\n", inventoryPath)
}

// verifyOverridePins refuses any override whose hand-pinned URL does not
// embed the version go.mod requires for that module. This is what makes a
// version bump loud for an override whose REPORTED row carries no version at
// all (mathutil's Unknown/Unknown): the reported-row pin cannot see the bump,
// but the go.mod requirement moved, and the stale URL no longer names it.
func verifyOverridePins(goMod string) error {
	for pkg, override := range overrides {
		var version string
		for line := range strings.SplitSeq(goMod, "\n") {
			fields := strings.Fields(strings.TrimSpace(line))
			if len(fields) >= 2 && fields[0] == pkg {
				version = fields[1]
				break
			}
		}
		if version == "" {
			return fmt.Errorf("the override for %q names a module go.mod does not require — remove the override or fix its key", pkg)
		}
		if !strings.Contains(override.url, "/"+version+"/") {
			return fmt.Errorf("the override URL for %q (%s) does not embed go.mod's required version %s — the module was bumped; re-read its license files and update the override", pkg, override.url, version)
		}
	}
	return nil
}

// tableFromReport turns go-licenses CSV rows (package,url,license) into the
// markdown table body, sorted by package path.
func tableFromReport(scanner *bufio.Scanner) (string, error) {
	rows := make([]string, 0, 64)
	applied := make(map[string]bool, len(overrides))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		fields := strings.Split(line, ",")
		if len(fields) != 3 {
			return "", fmt.Errorf("malformed report line (want 3 comma-separated fields): %q", line)
		}
		pkg, url, license := fields[0], strings.ReplaceAll(fields[1], `\`, "/"), fields[2]
		if pkg == ownModule || strings.HasPrefix(pkg, ownModule+"/") {
			continue
		}
		if override, ok := overrides[pkg]; ok {
			if url != override.reportedURL || license != override.reportedLicense {
				return "", fmt.Errorf("the override for %q was verified against a report of (%s, %q) but go-licenses now reports (%s, %q) — re-read the pinned version's license files and update the override", pkg, override.reportedLicense, override.reportedURL, license, url)
			}
			url, license = override.url, override.license
			applied[pkg] = true
		} else if license == "Unknown" || url == "Unknown" {
			return "", fmt.Errorf("go-licenses reports %q as %s at %q and no override is recorded — read the pinned version's license file and add one", pkg, license, url)
		}
		if !strings.HasPrefix(url, "https://") {
			return "", fmt.Errorf("license URL for %q is not a portable https link (%q) — a compliance table must not carry a dead or machine-local link; record an override", pkg, url)
		}
		rows = append(rows, fmt.Sprintf("| `%s` | %s | [license text](%s) |", pkg, license, url))
	}
	if err := scanner.Err(); err != nil {
		return "", err
	}
	if len(rows) == 0 {
		return "", fmt.Errorf("the report on stdin is empty — run go-licenses report ./cmd/ovumcy and pipe its output in")
	}
	for pkg := range overrides {
		if !applied[pkg] {
			return "", fmt.Errorf("the override for %q matched no reported row — the dependency left the graph or go-licenses renamed its row; re-verify and update or remove the override", pkg)
		}
	}
	sort.Strings(rows)
	return "| Package | License | Text |\n| --- | --- | --- |\n" + strings.Join(rows, "\n"), nil
}

// replaceBlock swaps the text between the markers for table, returning the
// updated document and the block it replaced.
func replaceBlock(document, table string) (updated, current string, err error) {
	start := strings.Index(document, beginMarker)
	end := strings.Index(document, endMarker)
	if start < 0 || end < 0 || end < start {
		return "", "", fmt.Errorf("%s does not carry the BEGIN/END generated-block markers", inventoryPath)
	}
	head := document[:start+len(beginMarker)]
	tail := document[end:]
	current = strings.TrimSpace(document[start+len(beginMarker) : end])
	updated = head + "\n" + table + "\n" + tail
	return updated, current, nil
}

// diffSummary names the rows present on one side only — enough to see which
// dependency moved without a real diff tool.
func diffSummary(current, want string) string {
	currentRows := map[string]bool{}
	for row := range strings.SplitSeq(current, "\n") {
		currentRows[row] = true
	}
	wantRows := map[string]bool{}
	var summary strings.Builder
	for row := range strings.SplitSeq(want, "\n") {
		wantRows[row] = true
		if !currentRows[row] {
			summary.WriteString("  missing: " + row + "\n")
		}
	}
	for row := range strings.SplitSeq(current, "\n") {
		if !wantRows[row] {
			summary.WriteString("  stale:   " + row + "\n")
		}
	}
	return strings.TrimRight(summary.String(), "\n")
}
