-- Two marks the privacy ledger (item 23) needs before it can say anything true
-- about what has left this instance. Both are nullable, both start NULL on every
-- existing row, and NO BACKFILL is performed or owed.
--
-- NO BACKFILL, webhook_last_delivered_at. The only per-owner data this schema
-- already holds about sending is the pair of watermarks
-- webhook_period_last_sent_cycle_start and webhook_ovulation_last_sent_cycle_start,
-- and they are not delivery times. Each is a compare-and-set value written
-- BEFORE the POST, holding a CYCLE ANCHOR rather than a clock reading, and it
-- stands unchanged for a send that was never accepted until the failure path
-- puts it back. A migration seeding this column from max() of the two would
-- write a claim time as a delivery time on every upgraded row and make that lie
-- permanent -- exactly the constraint the ledger exists to respect. An upgraded
-- instance says "no delivery recorded" until one is, which is the true
-- statement.
--
-- The column is written in exactly one place: after the notify pass gets a 2xx
-- from the endpoint, through MarkWebhookDelivered, pinned to the
-- webhook_config_version the delivering pass read. It is cleared in the same
-- UPDATE that writes webhook_url whenever the destination changes, is removed,
-- or its stored ciphertext no longer opens, and by the clear-data wipe alongside
-- both watermarks -- a mark must never outlive the endpoint it was about.
--
-- NO BACKFILL, calendar_feed_key_epoch. It holds the opaque identifier of the
-- verification regime a feed token was minted under (security.CalendarFeedKeyEpoch,
-- derived from SECRET_KEY). No value can be recomputed for a token minted before
-- this migration: the epoch of the key that signed it is recorded nowhere, and
-- deriving it from the CURRENT key would assert that every legacy row was minted
-- under the running regime -- the one claim the column exists to be able to
-- deny. NULL means "issued before this was recorded", which is what the instance
-- actually knows. It is stamped only by SaveCalendarFeedToken, in the same
-- UPDATE as the token triple, so no new writer of a feed access column appears.
-- Revoke and both bulk disarms leave it alone.
--
-- CORRECTION to migration 038. That file names SaveWebhookSettings,
-- UpdateReminderLeadDays and ClearAllDataAndResetSettings as the COMPLETE set of
-- webhook_config_version writers and says a fourth added later owes the same
-- advance. The rule is about writers of the DELIVERY CONFIGURATION, not about
-- writers of the users row. MarkWebhookDelivered is the second kind and must NOT
-- advance the epoch: the epoch is pinned once per owner OUTSIDE the reminder
-- loop, and advancing it after a period delivery would make that same pass lose
-- the ovulation claim it is about to take. A later writer owes the advance if
-- and only if it changes WHETHER, WHERE or HOW EARLY delivery happens.
--
-- Neither column is indexed: both are read one row at a time, by owner id, on
-- the settings path.
--
-- The migration runner skips any ADD COLUMN whose column already exists, so this
-- file is idempotent across clean installs and rolling deploys. Rollback
-- (forward-only repo) is documented in the commit body, not here.
--
-- NOTE: keep prose in this file free of semicolons -- the migration runner
-- splits statements on the semicolon character without stripping SQL comments,
-- so a semicolon inside a comment is mis-parsed as a statement boundary.

ALTER TABLE users ADD COLUMN webhook_last_delivered_at DATETIME;
ALTER TABLE users ADD COLUMN calendar_feed_key_epoch TEXT;
