-- Postgres mirror of migrations/038_webhook_config_version.sql (finding
-- PRIV-1 / SEC-01). Same version number and basename so schema history stays
-- aligned across engines.
--
-- webhook_config_version is the monotonic revocation epoch of an owner's
-- delivery configuration. Four writers advance it, each in the same statement
-- that performs its own write, and that is the COMPLETE set of DELIVERY
-- CONFIGURATION writers rather than an illustration -- a later one owes the same
-- advance: SaveWebhookSettings (a save, a disable, an endpoint replacement, a
-- removal), RemoveWebhookDestination (withdrawing the endpoint on its own, which
-- the save cannot express without also writing reminder_lead_days and both
-- per-kind opt-ins), UpdateReminderLeadDays (the shared banner-and-webhook lead
-- window, which the notify pass places its reminder from), and
-- ClearAllDataAndResetSettings.
--
-- What obliges a writer is what it CHANGES, never that it touched the users row.
-- MarkWebhookDelivered (migration 039) writes that row after a 2xx and must NOT
-- advance this column: it records that delivery happened, changing neither
-- WHETHER, WHERE nor HOW EARLY it happens. Advancing there would also break the
-- pass doing the delivering -- the epoch is pinned once per owner OUTSIDE the
-- reminder loop, so a bump after a period delivery loses the ovulation claim of
-- that same pass.
--
-- The pre-delivery watermark claim pins the value the claiming pass's snapshot
-- carried, so a pass that read the configuration before a revocation can no
-- longer win a claim and POST to the revoked endpoint. Clear-data ADVANCES the
-- counter rather than resetting it, because a reset would hand a revoked
-- snapshot its own value back. Existing rows start at 0 and nothing is owed to
-- them: migrations run at boot before the listener, so no pass spans the
-- upgrade. ClaimWebhookWatermark carries the whole predicate.
--
-- ALTER TABLE ADD COLUMN IF NOT EXISTS keeps the migration idempotent across
-- the postgres test bootstrap and rolling deploys (in addition to the runner's
-- own already-exists skip). Rollback (forward-only repo) is documented in the
-- commit body, not here.

ALTER TABLE users ADD COLUMN IF NOT EXISTS webhook_config_version INTEGER NOT NULL DEFAULT 0;
